View Multiple Buckets
NASA-PDS/s3-browser-cloudfront pull request #30
Opened 2024-04-18 19:13 UTC by eddiesarevalo

## 🗒️ Summary
Multiple buckets can now be viewed at once.

## ⚙️ Test Data and/or Report
Set up normally as in the readme if you have access to MCP and AWS.

A faster way is to switch to this branch. Then run `npm run build`, then run "python -m SimpleHTTPServer 9001" on the root directory of the project.
Open a browser to localhost:9001 then verify everything runs. (You might need a CORS extension for your browser to get around CORS blocks).

## ♻️ Related Issues
- fixes https://github.com/NASA-PDS/s3-browser-cloudfront/issues/22

2024-04-18 19:33 UTC, nutjob4life commented
`python -m SimpleHTTPServer 9001` only works in Python 2, which reached end-of-life on January 1st, 2020!

The modern equivalent would be `python3 -m http.server`

2024-04-18 19:37 UTC, nutjob4life requested changes
Looks pretty good otherwise!

2024-04-18 19:37 UTC, nutjob4life commented on src/index.html
> +      // MIT License
I thought we were using Apache License v2? 🤔

2024-04-18 19:37 UTC, nutjob4life commented on src/index.html
> +            <p class="footerLinksTitle">PLANETARY DATA SYSTEM</p>
Should this be `Planetary Data System` and the CSS class `footerLinksTitle` should have `text-transform: uppercase`?

2024-04-24 20:00 UTC, jordanpadams approved these changes

2024-04-24 20:01 UTC, jordanpadams commented
@eddiesarevalo is this build expected to fail on Node.js 16.x and 18.x?

2024-04-24 20:58 UTC, eddiesarevalo commented
@jordanpadams it works on node v16 and v18. I can add an nvmrc file though so that nvm could take care to use the latest v20

2024-04-24 21:08 UTC, anilnatha commented
@jordanpadams The Node.js tests breaking are something we need to address in other repos too. For this repo, I think we should remove the Node.js 14.x and 16.x tests as they don't provide any value. Both 14 and 16 versions are no longer supported by Node.js

2024-04-24 21:53 UTC, jordanpadams commented
@anilnatha @eddiesarevalo copy. will remove 14 and 16, for v18, how should we update your branch build so we build successfully?

```
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        token: ${{secrets.ADMIN_GITHUB_TOKEN || github.token}}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
```
It looks like it is failing on the npm test because there is no test file.

2024-04-24 21:53 UTC, merged